### PR TITLE
Update README.md and change a quirk

### PR DESCRIPTION
**Pull request by miffi**
Hello again. For some reason (I really have no idea why I'm doing this) I came back to this and decided to smoothen out some of the edges. Firstly I've changed some of the behaviour of the  plugin such that it returns a word as is if it is all caps or in the exclusion list. Secondly I've added some documentation lining out the title casing rules, two caveats I've found, and a variable for the exclusion list. Please feel free to review this PR if you have the time.

### CODE REVIEW

**Comment by christoomey** [comment]
Hey @Mifff-ia, this looks like a nice set of updates. Thanks for sharing! Would you mind rebasing onto the current `master` as it looks like there's a conflict?

**Comment by Mifff-ia** [comment]
I went and resolved the conflict, it should be okay to merge now.

**Comment by huyz** [comment]
Let's merge this :)

**Comment by christoomey** [comment]
Hi @huyz, thanks for the bump here. @miffi thank you for the updates here (and apologies for the _very long_ delay). I reworded your README changes slightly and merged as 69a697c54a08ca5603cb757b4d4f78cd4b567549 (added you as a co-author).

Apologies if I'm missing something, but I found myself confused by the functional changes in the plugin file. The `g:titlecase_excluded_words` functionality and acronym support already exists as far as I can tell. I'm wondering if some things were added since you opened this (again, sorry the delay here), but I've opted to not include the plugin changes (now would go in the autoload file). Please feel free to re-open as a distinct change if I'm missing something, and again, thanks for the updates here!

**Comment by miffi** [comment]
The functional bug is a semantic change on my end. If I recall correctly, my thoughts while writing this PR was that if `g:titlecase_excluded_words` had a word with mixed case, the plugin would return that. However, as it is now, that branch would just not get excluded in that case.  I have no clue how I thought that that would work. :sweat_smile:

I agree that this PR should be closed. Thanks for incorporating the changes to the README. :)

**Pull request closed without merging**
